add riscv64

diff --git a/bin/system-setup b/bin/system-setup
--- a/bin/system-setup
+++ b/bin/system-setup
@@ -19,64 +19,55 @@ DEPS=(
     libncurses5-dev
     mtools
     parallel
-    python
-    qemu-utils
+    python3
+    qemu-img
     quilt
     rsync
     texinfo
     unzip
     wget
-    xz-utils
+    xz
 )
 
-apt_get() {
+yum_get() {
     local ret=""
     if [ "$1" != "update" ] && ! $_APT_UPDATED; then
-        error "updating apt"
-        apt_get update >/dev/null || {
+        error "updating yum"
+        sudo yum update -y >/dev/null || {
             ret=$?;
-            error "failed to update apt [$ret]";
+            error "failed to update yum [$ret]";
             return $ret;
         }
         _APT_UPDATED=true
     fi
-    sudo DEBIAN_FRONTEND=noninteractive apt-get --quiet \
-        --assume-yes "$@" </dev/null
+    sudo yum install -y "$@" >/dev/null
 }
 
 filter_installed_packages() {
     # write to stdout, a list of packages not installed locally
-    local fmt='${Package} ${Version}\n'
-    LC_ALL=C dpkg-query --show "--showformat=${fmt}" "$@" 2>&1 | awk '
-        $0 ~ /[Nn]o packages/ {
-            sub("[.]$","",$NF);
-            pkgs[n]=$NF;
-            n=n+1;
-        }
-        $2 == "" {
-                pkgs[n]=$1;
-                n=n+1;
-        };
-        END { for(p in pkgs) {printf("%s ",pkgs[p])}; printf("\n"); }' n=0
+    local installed_packages
+    installed_packages=$(yum list installed "$@" 2>&1)
+    echo "$installed_packages" | grep -Eo '^[^ ]+' | grep -vxFf <(echo "$installed_packages" | grep -Eo '^[^ ]+') - |
+    awk '{print $1}'
 }
 
-apt_install() {
+yum_install() {
     local needed
     needed=$(filter_installed_packages "$@")
     [ -z "$needed" ] && return 0
     error "installing: $needed"
-    apt_get install "$@"
+    yum_get install "$@"
 }
 
-dist_id=$(lsb_release --short --id) || fail "failed: lsb_release --short --id"
+dist_id=$(cat /etc/os-release | grep '^ID=' | cut -d'=' -f2) || fail "failed: unable to determine OS ID"
 case "$dist_id" in
-    *buntu) :;;
-    *) fail "do not know how to setup $dist_id";;
+    *openEuler*) :;;
+    *) fail "do not know how to set up $dist_id";;
 esac
 
-ver=$(lsb_release --short --release)
-[[ "$ver" < "14.04" ]] &&
-    fail "building not supported prior to 14.04"
+ver=$(cat /etc/os-release | grep '^VERSION_ID=' | cut -d'=' -f2 | tr -d '"')
+[[ "$ver" < "20.03" ]] &&
+    fail "building not supported prior to 20.03"
 
 me=$(readlink -f "$0")
 myd=$(dirname "$me")
@@ -87,7 +78,7 @@ elif [ -f "$PWD/cirros/fixup-fs" ]; then
     CIRROS_D="$PWD/cirros"
 fi
 
-apt_install "${DEPS[@]}"
+yum_install "${DEPS[@]}"
 
 if [ -z "$CIRROS_D" ]; then
     error "getting $CIRROS_BRANCH to $PWD/cirros"
